application:
  data-dir: imagedir/
  jwtSecret: ${API_KEY:defaultSecretKey}
  jwtExpirationMs: 86400000
server.port: ${PORT:8080}
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:inventory}
    username: ${DB_USER:root}
    password: ${DB_PASS:}
  messages.basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
springdoc.swagger-ui.path: /api/swagger-ui.html
springdoc.api-docs.path: /api/docs